name: integration test

on:
  workflow_dispatch:
    braches: [main]
  schedule:
    - cron: '0 19 * * *'

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run github action
        uses: ./
        id: github_grass
        with:
          githubAccounts: 'tomoya-k31'
      - name: Check outputs
        run: |
          echo "${{ steps.github_grass.outputs.githubGrassOutputImagePath }}"
          ls -la /github/workspace/
          ls -la /github/workspace/dist/
